name: Create release   
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v?[0-9]+\.[0-9]+\.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    - name: Restore dependencies
      run: dotnet restore AnimeVideoDownloader/DesktopDownloader/DesktopDownloader.csproj
    - name: Build
      run: dotnet publish AnimeVideoDownloader/DesktopDownloader/DesktopDownloader.csproj  -c Release -o Publish 
    - uses: papeloto/action-zip@v1
      with:
        files: Publish/ 
        recursive: false
        dest: Downloader.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: Downloader.zip

    
